package com.example.hideboatsails;

import com.google.inject.Provides;
import javax.inject.Inject;

import net.runelite.api.Client;
import net.runelite.api.GameObject;
import net.runelite.api.Tile;
import net.runelite.api.events.GameObjectDespawned;
import net.runelite.api.events.GameObjectSpawned;
import net.runelite.api.events.GameStateChanged;
import net.runelite.api.GameState;

import net.runelite.client.config.ConfigManager;
import net.runelite.client.eventbus.Subscribe;
import net.runelite.client.plugins.Plugin;
import net.runelite.client.plugins.PluginDescriptor;

import java.util.HashSet;
import java.util.Set;

@PluginDescriptor(
        name = "Hide Boat Sails",
        description = "Hides boat sails when not navigating",
        tags = {"boats", "sails", "hide"}
)
public class HideBoatSailsPlugin extends Plugin
{
    private static final int SAIL_OBJECT_ID = 60473;

    @Inject
    private Client client;

    @Inject
    private HideBoatSailsConfig config;

    /**
     * Store sails that we hide so we can restore them later.
     */
    private fi
